### ISSUE TITLE
.prettierrc 파일 생성

### ISSUE THREAD

**Issue by seokh1213** [HongSiKi/PaintingDiary#4]
- .prettierrc 파일 생성
- 작은따옴표가 기본

참고:
- https://prettier.io/docs/en/configuration.html

**Comment by 1two13** [comment]
1. 터미널에 `npm i -D prettier eslint-config-prettier` 입력
2. `.prettierrc` 파일 추가 및 [feature/prettierrc](https://github.com/HongSiKi/PaintingDiary/tree/feature/prettierrc) 브랜치 생성
3. 해당 브랜치에 push
